language: ruby
rvm:
- 2.3.0
deploy:
  provider: heroku
  api_key:
    secure: H3ixeOKR9kqX6Fo4FZK/HX8No5fjqdjINgN0hZjlVy5FcRa5TwpBahdBrqlsRqvnqIUK75Rp6rSn4D1YieMY9Kv/4elEfHMNYzbfLP8PSkigU1OPQOxAYl/VilqYuVI5ElmH3tyPeevymgmeJiuTiupPWbQwsKpF84rftgpBSnPh92bwGPf3ac1Cnvhpp7cPv+jVNAN88sVleC//8MjPJSk4uEpZo4SolyVv2A16zjnRnI+ROG++Y2I1zzACLM1IsoH+hclNb/SzfFs2FvnPT0yGO7o1k+mbmv2MLMsiOx0DGLzf1lZRiRnBN/ophnWOQY+FdH/QV+KDjAa0qf5SkA0LxbmvyyEnhPzEBstTqweJYmjGrHeWFoLq3oHM1YtYEBSg0uSNq5XxvcuRF0LL284ctVho8EOMnzLqS91SzdnypoUE9l1jBzkpMKSFjB2EHmjCU0C+5mxlNl9s/flluR5ls0TIcCV6bfG8LVZGspkJSxvra3JPk1hYv/ADHD9fZdNjuGnRCogZsYoLM+IhUCLwe61wVCeW/6Sr4ZI9Rnqmo0VJgKTxx4YBB+GVTNR2h8rUNRpaQbnZ9yRz3ASTVk11LNxs876k8+dtFNCUk7hS0p0OqE5Ib5pI76M4WgkeaX4t+UcqboZDy98o0D/yMDn1Gl2FSmAbnuGWX55WmpI=
  run: "rake db:migrate"
  app: quiet-ravine-16218
  on:
    repo: VMoniz/projet
