language: ruby
rvm:
- 2.3.0
- 2.2.4
deploy:
  provider: heroku
  api_key:
    secure: E9s0bmSKjmfWDTc8bYdWibGk5Lu1hboa78yvXOpkpZHfdDjBlpawW4pOhqIb0GYJnnRj8wCKEFf/ZRO0XtEtqGwU/edUrpnbbjfcXVYd6+lkPYuNzuCed/htHO4lwO+/KB3JMvXWuLO2L7w1WmHy7eNaWC3tOAFTfcMvTPIGep6sD6frXSWdpKjHvctzVH7Xl/v2sDjCStrl0EhOXVvPxg7tmoKHbFeFXTqa93V8ykZbPzhY2Bg8Hv0699FsdqogrDEDIp2OaUYRJUqQP5dgId9YHAklEwiR01wSxa/xggDkK9C1YGKU8aFtfIRIBLzfeLAVX/VOqnGtPRmSAThn5llibMKWf2mWSOmlyGP8oSPLTOmHoh8aABh0fTQdd81LFjKRWQjAXMSwQcjY844AkO0FcFrJ33C7DtpZjfVED2ix86H546/2s/l4e/YeKvhqCd2J6pA4UeOwT9gUWXg8PeXFSVmOtzdRa9jHdNenHijHEVqLSVMdr5/bbUytExXGX3St38DrLyHsmVSqG+5EhPHRmPDtK3O1nQ4Eymu+UyJiTPYnnqDv7eLTrBMryuXRkiHf9jZo1doJijdag2GpDgN4v/Bt9oV4/gZpfaWhyl6l4zfbrwlJQ5OiP4hLiaHdSa7c/Ya8gRj/DxV47N8iUca8uAgDEEKlGRGQp2QyneI=
  app: projet
  on:
    repo: VMoniz/projet
