language: ruby
rvm:
- 2.3.0
- 2.2.4
deploy:
  provider: heroku
  api_key:
    secure: JVwjaGj6TZVckgEA9XZKk+rE2XebSqiuB/qVuQgCpfxzham2c/hNIFJng/d+RfTQhAUIyKMJAY0UzyRkKwjWlRqLU83/XsLzfq+pZQt17Pxl9yYgdqM22KRcfjVQVvN/ogbXVk7QAClGSbMID3qSWCrxab0Lm1oomq+7mAD3j4CvStQ98yjk9TPFpGUzJmI04UhusfPR9Azdkxs9OBZnY5c/2QRNUY2Ogq6EjaCiaqMZckcnPoGFKqZl6mut/imaHNhXQYYvHFqiT87ZPtA8QmIKWNkTPh5i8vNGTTT3LJ4Vw/yLxrn26ETOWiy0XIeC6PhcqtuDKU9bjyw3n3sH4BIe7MDUWcdNT9rglU7uvyw547rM2TJrO6fxP0eKxSbQ+p/XJM8oTEcxK62134vczLrjI6KE4nBctOSf1+LN8mh66ePpdcxulH11X036PWmtVJ2ObryRFcLqYipWGske9qUyvQ8dRpv2XcCK2CecTO62V4JlfKGMwN6O3zXkEjEfCxA7mx6+ACSDlQaBP6DUl3KTCYNOi+3VTT9SI95tX3l7gp0jQaoawmjAUzGogQaFfbzJdVB18ivGYEJ+fUAGT8gHUCNbVLyc++udosEYACN96K/Ij9qFILfV8O4HC7BRiAl5g6R2BRc2do4VAruuatLvMR8TUR92yz3J89lTb4Y=
  app: quiet-ravine-16218
  on:
    repo: VMoniz/projet
